"""Count Arabic (lang_id=22) translation coverage in currentLanguage_utf8.sql.

Read-only static analysis for §13 Arabic/i18n runtime evidence.
Streams the ~250k-line SQL dump, does not load it into memory.
"""
import re
import sys

SRC = r'D:\OpenEmr\contrib\util\language_translations\currentLanguage_utf8.sql'
OUT = r'D:\OpenEmr\docs\discovery\openemr-decision-evidence\evidence\manifests\openemr-arabic-string-coverage.txt'

insert_def_re = re.compile(r'^INSERT INTO `lang_definitions` VALUES\s*(.*)$', re.IGNORECASE)
insert_const_re = re.compile(r'^INSERT INTO `lang_constants` VALUES\s*(.*)$', re.IGNORECASE)
# lang_definitions tuple: (def_id, cons_id, lang_id, 'definition')
def_tuple_re = re.compile(r'\(\s*\d+\s*,\s*(\d+)\s*,\s*(\d+)\s*,')
# lang_constants tuple: (cons_id, 'constant_name')  — just count tuple openings
const_tuple_re = re.compile(r"\(\s*\d+\s*,\s*'")

total_defs = 0
total_consts = 0
arabic_rows = 0
unique_cons_total = set()
unique_cons_in_arabic = set()
lang_id_histogram = {}

with open(SRC, 'r', encoding='utf-8', errors='replace') as f:
    for line in f:
        m = insert_def_re.match(line)
        if m:
            for tm in def_tuple_re.finditer(m.group(1)):
                total_defs += 1
                cons_id = int(tm.group(1))
                lang_id = int(tm.group(2))
                unique_cons_total.add(cons_id)
                lang_id_histogram[lang_id] = lang_id_histogram.get(lang_id, 0) + 1
                if lang_id == 22:
                    arabic_rows += 1
                    unique_cons_in_arabic.add(cons_id)
            continue
        mc = insert_const_re.match(line)
        if mc:
            total_consts += len(const_tuple_re.findall(mc.group(1)))

lines = []
lines.append('# Arabic (lang_id=22) translation coverage — currentLanguage_utf8.sql')
lines.append('# Generated by tools/discovery/openemr-decision-evidence/count-arabic-translations.py')
lines.append('')
lines.append(f'source_file: contrib/util/language_translations/currentLanguage_utf8.sql')
lines.append(f'total_insert_lang_definitions_tuples: {total_defs}')
lines.append(f'total_insert_lang_constants_tuples:   {total_consts}')
lines.append(f'unique_cons_id_referenced_by_any_definition_row: {len(unique_cons_total)}')
lines.append(f'rows_where_lang_id_eq_22_Arabic: {arabic_rows}')
lines.append(f'unique_cons_id_with_an_Arabic_definition: {len(unique_cons_in_arabic)}')
if unique_cons_total:
    pct_all = 100.0 * len(unique_cons_in_arabic) / len(unique_cons_total)
    lines.append(f'arabic_coverage_vs_unique_cons_ids_ever_translated_pct: {pct_all:.2f}')
if total_consts:
    pct_cons = 100.0 * len(unique_cons_in_arabic) / total_consts
    lines.append(f'arabic_coverage_vs_lang_constants_table_size_pct: {pct_cons:.2f}')
lines.append('')
lines.append('# Per-language row counts (lang_id -> INSERT tuple count in lang_definitions):')
for lid in sorted(lang_id_histogram):
    lines.append(f'lang_id={lid:>3}  rows={lang_id_histogram[lid]}')

open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
for ln in lines:
    print(ln)
print('WROTE', OUT)
