<?php

/**
 * Parsed command line for the branding token generator.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Branding;

/**
 * Hand-rolled rather than Symfony Console so the generator stays dependency
 * free and can run from a bare checkout before `composer install`.
 *
 * Defaults are literals, never environment reads, because an option that
 * varies by host would leak into the generated bytes.
 */
final readonly class CliOptions
{
    public const DEFAULT_OUTPUT_DIRECTORY = 'tools/branding/output-preview';
    public const DEFAULT_FONT_URL_BASE = '../assets/fonts/thiqa';

    private function __construct(
        public string $repoRoot,
        public string $outputDirectory,
        public string $fontUrlBase,
        public bool $check,
        public bool $help,
    ) {
    }

    /**
     * @param list<string> $arguments argv without the script name
     */
    public static function parse(array $arguments, string $defaultRepoRoot): self
    {
        $repoRoot = $defaultRepoRoot;
        $outputDirectory = null;
        $fontUrlBase = self::DEFAULT_FONT_URL_BASE;
        $check = false;
        $help = false;

        foreach ($arguments as $argument) {
            [$name, $value] = self::split($argument);
            switch ($name) {
                case '--repo-root':
                    $repoRoot = self::requireValue($name, $value);
                    break;
                case '--out-dir':
                    $outputDirectory = self::requireValue($name, $value);
                    break;
                case '--font-url-base':
                    $fontUrlBase = self::requireValue($name, $value);
                    break;
                case '--check':
                    $check = true;
                    break;
                case '--help':
                case '-h':
                    $help = true;
                    break;
                default:
                    throw new GeneratorException(sprintf('Unknown option "%s". Try --help.', $name));
            }
        }

        $repoRoot = rtrim(strtr($repoRoot, '\\', '/'), '/');
        if ($repoRoot === '') {
            throw new GeneratorException('--repo-root must not be empty.');
        }

        $outputDirectory ??= $repoRoot . '/' . self::DEFAULT_OUTPUT_DIRECTORY;

        return new self($repoRoot, rtrim(strtr($outputDirectory, '\\', '/'), '/'), $fontUrlBase, $check, $help);
    }

    public static function usage(): string
    {
        return implode("\n", [
            'Usage: php ' . GeneratedHeader::GENERATOR . ' [options]',
            '',
            'Generates the Thiqa branding artefacts from the brand token sources.',
            '',
            'Options:',
            '  --repo-root=DIR       Repository root (default: the checkout this script lives in)',
            '  --out-dir=DIR         Where to write artefacts (default: ' . self::DEFAULT_OUTPUT_DIRECTORY . ')',
            '  --font-url-base=URL   URL prefix for @font-face src (default: ' . self::DEFAULT_FONT_URL_BASE . ')',
            '  --check               Do not write; exit 3 if any artefact on disk differs',
            '  -h, --help            Show this help',
            '',
        ]) . "\n";
    }

    /**
     * @return array{string, ?string}
     */
    private static function split(string $argument): array
    {
        $position = strpos($argument, '=');
        if ($position === false) {
            return [$argument, null];
        }

        return [substr($argument, 0, $position), substr($argument, $position + 1)];
    }

    private static function requireValue(string $name, ?string $value): string
    {
        if ($value === null || $value === '') {
            throw new GeneratorException(sprintf('Option "%s" requires a value, e.g. %s=path.', $name, $name));
        }

        return $value;
    }
}
