<?php

/**
 * A validated six-digit hexadecimal colour.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Branding;

/**
 * Parsed at the token-document boundary so no downstream renderer has to
 * re-validate. Normalised to upper case so casing drift in the source JSON
 * cannot change generated bytes.
 */
final readonly class HexColor
{
    private function __construct(public string $value)
    {
    }

    /**
     * @param string $context token path, used only in the failure message
     */
    public static function fromString(string $raw, string $context): self
    {
        if (preg_match('/^#[0-9A-Fa-f]{6}$/', $raw) !== 1) {
            throw new GeneratorException(sprintf(
                'Token "%s" must be a six-digit hex colour like #0B1B4D, got "%s".',
                $context,
                $raw,
            ));
        }

        return new self('#' . strtoupper(substr($raw, 1)));
    }

    /**
     * CSS `rgba()` form at the given alpha, for scrims and backdrops.
     */
    public function toRgba(float $alpha): string
    {
        if ($alpha < 0.0 || $alpha > 1.0) {
            throw new GeneratorException(sprintf('Alpha must be between 0 and 1, got %s.', var_export($alpha, true)));
        }

        $rgb = [];
        foreach ([1, 3, 5] as $offset) {
            $channel = hexdec(substr($this->value, $offset, 2));
            if (!is_int($channel)) {
                throw new GeneratorException(sprintf('Colour "%s" could not be decomposed into RGB.', $this->value));
            }
            $rgb[] = (string) $channel;
        }

        return sprintf('rgba(%s, %s)', implode(', ', $rgb), rtrim(rtrim(number_format($alpha, 2, '.', ''), '0'), '.'));
    }
}
