<?php

/**
 * Writes generated artefacts, or verifies the ones already on disk.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Branding;

/**
 * Writes are binary-mode `file_put_contents`, so the LF line endings the
 * renderers build survive on Windows hosts too. `verify()` backs the CI check
 * that fails when a generated file has been hand-edited.
 */
final readonly class OutputWriter
{
    public function __construct(private string $outputDirectory)
    {
    }

    /**
     * @param list<GeneratedFile> $files
     *
     * @return list<string> repo-relative-ish names written, in input order
     */
    public function write(array $files): array
    {
        if (!is_dir($this->outputDirectory) && !mkdir($this->outputDirectory, 0o755, true) && !is_dir($this->outputDirectory)) {
            throw new GeneratorException(sprintf('Output directory "%s" could not be created.', $this->outputDirectory));
        }

        $written = [];
        foreach ($files as $file) {
            $target = $this->target($file);
            if (file_put_contents($target, $file->contents) === false) {
                throw new GeneratorException(sprintf('Generated file "%s" could not be written.', $file->name));
            }
            $written[] = $file->name;
        }

        return $written;
    }

    /**
     * @param list<GeneratedFile> $files
     *
     * @return list<string> names that are missing or differ from the generated bytes
     */
    public function verify(array $files): array
    {
        $drifted = [];
        foreach ($files as $file) {
            $target = $this->target($file);
            if (!is_file($target)) {
                $drifted[] = $file->name . ' (missing)';
                continue;
            }
            $onDisk = file_get_contents($target);
            if ($onDisk === false) {
                $drifted[] = $file->name . ' (unreadable)';
                continue;
            }
            if ($onDisk !== $file->contents) {
                $drifted[] = $file->name . ' (differs)';
            }
        }

        return $drifted;
    }

    private function target(GeneratedFile $file): string
    {
        return rtrim($this->outputDirectory, "/\\") . '/' . $file->name;
    }
}
