<?php

/**
 * Parsed command line for the product identity artefact generator.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Branding;

/**
 * Hand-rolled for the same reason as {@see CliOptions}: the generator must run from a
 * bare checkout, before `composer install`, so it takes no dependency on Symfony Console.
 *
 * Every default is a literal, never an environment read. An option that varied by host
 * would leak into the generated bytes and break the byte-for-byte reproducibility the
 * `--check` mode depends on.
 *
 * `--profile` and `--out-file` exist so the isolated suite can drive the real entry point
 * against fixtures instead of the shipped profile. CI runs the generator with **no**
 * options, which is what keeps `config/branding-profile.json` the single authority.
 */
final readonly class ProductIdentityCliOptions
{
    /** Where the artefact the application loads actually lives, repo-relative. */
    public const DEPLOYED_PATH = 'library/' . ProductIdentityGenerator::ARTEFACT_NAME;

    private function __construct(
        public string $repoRoot,
        public string $profilePath,
        public string $outputFile,
        public bool $check,
        public bool $help,
    ) {
    }

    /**
     * @param list<string> $arguments argv without the script name
     */
    public static function parse(array $arguments, string $defaultRepoRoot): self
    {
        $repoRoot = $defaultRepoRoot;
        $profilePath = null;
        $outputFile = null;
        $check = false;
        $help = false;

        foreach ($arguments as $argument) {
            [$name, $value] = self::split($argument);
            switch ($name) {
                case '--repo-root':
                    $repoRoot = self::requireValue($name, $value);
                    break;
                case '--profile':
                    $profilePath = self::requireValue($name, $value);
                    break;
                case '--out-file':
                    $outputFile = self::requireValue($name, $value);
                    break;
                case '--check':
                    $check = true;
                    break;
                case '--help':
                case '-h':
                    $help = true;
                    break;
                default:
                    throw new GeneratorException(sprintf('Unknown option "%s". Try --help.', $name));
            }
        }

        $repoRoot = self::normalise($repoRoot);
        if ($repoRoot === '') {
            throw new GeneratorException('--repo-root must not be empty.');
        }

        return new self(
            $repoRoot,
            self::normalise($profilePath ?? $repoRoot . '/' . ProductIdentityGenerator::PROFILE_PATH),
            self::normalise($outputFile ?? $repoRoot . '/' . self::DEPLOYED_PATH),
            $check,
            $help,
        );
    }

    public static function usage(): string
    {
        return implode("\n", [
            'Usage: php ' . GeneratedHeader::PRODUCT_IDENTITY_GENERATOR . ' [options]',
            '',
            'Derives ' . self::DEPLOYED_PATH . ' from the authoritative branding profile.',
            'The artefact is the product identity that bootstrap code reads before a database exists.',
            '',
            'Options:',
            '  --repo-root=DIR    Repository root (default: the checkout this script lives in)',
            '  --profile=FILE     Branding profile to read (default: ' . ProductIdentityGenerator::PROFILE_PATH . ')',
            '  --out-file=FILE    Artefact to write (default: ' . self::DEPLOYED_PATH . ')',
            '  --check            Do not write; exit 3 if the artefact on disk differs',
            '  -h, --help         Show this help',
            '',
            'Exit codes: 0 success, 1 profile/validation failure, 2 bad usage, 3 --check found drift.',
            '',
        ]) . "\n";
    }

    /**
     * @return array{string, ?string}
     */
    private static function split(string $argument): array
    {
        $position = strpos($argument, '=');
        if ($position === false) {
            return [$argument, null];
        }

        return [substr($argument, 0, $position), substr($argument, $position + 1)];
    }

    private static function requireValue(string $name, ?string $value): string
    {
        if ($value === null || $value === '') {
            throw new GeneratorException(sprintf('Option "%s" requires a value, e.g. %s=path.', $name, $name));
        }

        return $value;
    }

    private static function normalise(string $path): string
    {
        return rtrim(strtr($path, '\\', '/'), '/');
    }
}
