<?php

/**
 * Renders `smart-style_light.json.twig` and `smart-style_dark.json.twig`.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Branding;

/**
 * Byte-shape matches the existing `templates/api/smart/smart-style_light.json.twig`:
 * a bare JSON object, four-space indent, the twelve keys in the same order, and
 * `logo_primary` left as the `{{ logo.primary }}` expression.
 *
 * The banner uses Twig's whitespace-trimming comment delimiters, so the rendered
 * response still begins at the opening brace and the wire format is unchanged.
 */
final readonly class SmartStyleTemplateRenderer
{
    private const INDENT = '    ';

    /**
     * Keys whose value is a Twig expression and must not be JSON-escaped.
     */
    private const RAW_KEYS = ['logo_primary'];

    public function render(SmartStyleContract $contract, Variant $variant): GeneratedFile
    {
        $values = $contract->values();
        if (count($values) !== 12) {
            throw new GeneratorException(sprintf(
                'The SMART style contract must carry exactly 12 keys, built %d.',
                count($values),
            ));
        }

        $lines = [
            sprintf(
                '{#- GENERATED by %s from brand/tokens/thiqa-tokens.json (%s). DO NOT EDIT. -#}',
                GeneratedHeader::GENERATOR,
                $variant->key(),
            ),
            '{',
        ];

        $index = 0;
        $last = count($values) - 1;
        foreach ($values as $key => $value) {
            $lines[] = self::INDENT
                . $this->encode($key) . ': ' . $this->encodeValue($key, $value)
                . ($index === $last ? '' : ',');
            $index++;
        }

        $lines[] = '}';

        return new GeneratedFile(
            sprintf('smart-style_%s.json.twig', $variant->key()),
            implode("\n", $lines) . "\n",
        );
    }

    private function encodeValue(string $key, string $value): string
    {
        if (in_array($key, self::RAW_KEYS, true)) {
            return '"' . $value . '"';
        }

        return $this->encode($value);
    }

    private function encode(string $value): string
    {
        $encoded = json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($encoded === false) {
            throw new GeneratorException(sprintf('Value "%s" could not be JSON encoded.', $value));
        }

        return $encoded;
    }
}
