<?php

/**
 * Renders and atomically places one tenant's generated token stylesheet.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Modules\SkyEagleBranding\Materialisation;

use OpenEMR\Modules\SkyEagleBranding\Tenant\SiteId;
use OpenEMR\Modules\SkyEagleBranding\Theme\ThemeVariant;
use OpenEMR\Modules\SkyEagleBranding\Token\CssVariableRenderer;
use OpenEMR\Modules\SkyEagleBranding\Token\TokenSet;

/**
 * The fallback static-file route of plan §3.2.2 option (b): a real stylesheet on disk
 * under the module tree, which is the only location `filterSafeLocalModuleFiles()`
 * accepts for a StyleFilterEvent path.
 *
 * Two guarantees, and they are the whole reason this class exists rather than a
 * `file_put_contents()` call inside the materialiser:
 *
 *  1. **A half-written stylesheet is never observable.** Content is staged beside the
 *     target and renamed over it (AtomicFileWriter). A reader sees revision n-1 whole
 *     or revision n whole, never a truncated `:root {`.
 *  2. **The output is byte-deterministic for equal inputs.** Declarations come from
 *     TokenSet::all(), which orders by the TokenKey enum rather than by insertion, and
 *     the header carries no timestamp and no revision number. Plan §3.8's invariant
 *     (iii) — a rollback reproduces byte-identical output — depends on that, and it is
 *     also what lets the materialiser skip a rewrite it does not need.
 *
 * The only selector emitted is the literal `:root`. CssVariableRenderer is structurally
 * incapable of producing a brace, so wrapping is done here, from a constant, and the
 * variant is distinguished by filename rather than by a computed selector.
 */
final readonly class TokenCssWriter
{
    /** The one selector this writer may emit. Not a parameter, and never will be. */
    private const SELECTOR = ':root';

    private const INDENT = '    ';

    /** Static, deterministic, and free of anything that changes between equal runs. */
    private const HEADER = "/* Generated by the SkyEagle branding materialiser. Do not edit. */";

    public function __construct(
        private CssVariableRenderer $renderer,
        private AtomicFileWriter $files,
        private TenantBrandingPaths $paths,
    ) {
    }

    /** The absolute path this writer would place the variant's stylesheet at. */
    public function targetPath(SiteId $site, ThemeVariant $variant): string
    {
        return $this->paths->tokenCssFile($site, $variant);
    }

    /**
     * The exact bytes the stylesheet would contain for this token set.
     *
     * Exposed so the materialiser can compare against what is already on disk and
     * decide the run is a no-op without writing anything (idempotence, plan §4.3 WP-2.8).
     */
    public function render(TokenSet $tokens): string
    {
        $declarations = $this->renderer->renderDeclarations($tokens);

        $body = '';
        foreach ($declarations as $declaration) {
            $body .= self::INDENT . $declaration . "\n";
        }

        return self::HEADER . "\n" . self::SELECTOR . " {\n" . $body . "}\n";
    }

    /**
     * The stylesheet currently on disk for this tenant and variant, or null if absent.
     *
     * @throws FilesystemException
     */
    public function currentContents(SiteId $site, ThemeVariant $variant): ?string
    {
        $path = $this->targetPath($site, $variant);
        if (!is_file($path)) {
            return null;
        }

        $contents = file_get_contents($path);
        if ($contents === false) {
            throw FilesystemException::notReadable($path);
        }

        return $contents;
    }

    /**
     * True when the on-disk stylesheet already matches this token set exactly.
     *
     * @throws FilesystemException
     */
    public function isCurrent(SiteId $site, ThemeVariant $variant, TokenSet $tokens): bool
    {
        return $this->currentContents($site, $variant) === $this->render($tokens);
    }

    /**
     * Write the stylesheet to a temporary name in the target directory. Nothing is live yet.
     *
     * Creates the tenant's directory when it does not exist — a tenant that has never
     * been materialised has no directory, and that is the normal first-run case rather
     * than an error.
     *
     * @throws FilesystemException
     */
    public function stage(SiteId $site, ThemeVariant $variant, TokenSet $tokens): StagedFile
    {
        return $this->files->stage($this->targetPath($site, $variant), $this->render($tokens));
    }
}
