<?php

/**
 * TokenCssWriter: deterministic bytes, one selector, atomic placement.
 *
 * @package   OpenEMR
 * @link      https://www.open-emr.org
 * @author    mohammedfouly1 <mselfouly2008@yahoo.com>
 * @copyright Copyright (c) 2026 mohammedfouly1
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

declare(strict_types=1);

namespace OpenEMR\Tests\Isolated\Modules\SkyEagleBranding\Materialisation;

use OpenEMR\Modules\SkyEagleBranding\Materialisation\AtomicFileWriter;
use OpenEMR\Modules\SkyEagleBranding\Materialisation\TenantBrandingPaths;
use OpenEMR\Modules\SkyEagleBranding\Materialisation\TokenCssWriter;
use OpenEMR\Modules\SkyEagleBranding\Tenant\SiteId;
use OpenEMR\Modules\SkyEagleBranding\Theme\ThemeVariant;
use OpenEMR\Modules\SkyEagleBranding\Token\ColorValue;
use OpenEMR\Modules\SkyEagleBranding\Token\CssVariableRenderer;
use OpenEMR\Modules\SkyEagleBranding\Token\DesignToken;
use OpenEMR\Modules\SkyEagleBranding\Token\TokenKey;
use OpenEMR\Modules\SkyEagleBranding\Token\TokenSet;
use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/materialisation_autoloader.php';

final class TokenCssWriterTest extends TestCase
{
    use TemporaryTreeTrait;

    private TokenCssWriter $writer;

    private AtomicFileWriter $files;

    private SiteId $site;

    private string $tree = '';

    protected function setUp(): void
    {
        $this->tree = $this->makeTree();
        $this->site = new SiteId('alpha');
        $this->files = new AtomicFileWriter();
        $this->writer = new TokenCssWriter(
            new CssVariableRenderer(),
            $this->files,
            new TenantBrandingPaths($this->tree . '/branding', $this->tree . '/sites'),
        );
    }

    protected function tearDown(): void
    {
        $this->removeTree();
    }

    private function tokens(): TokenSet
    {
        return new TokenSet(
            ThemeVariant::Light,
            new DesignToken(TokenKey::LinkDefault, new ColorValue('#2C5F94')),
            new DesignToken(TokenKey::Background, new ColorValue('#FAFAF8')),
        );
    }

    public function testTheRenderedFileIsAOneSelectorRuleBlock(): void
    {
        $css = $this->writer->render($this->tokens());

        self::assertSame(
            "/* Generated by the SkyEagle branding materialiser. Do not edit. */\n"
                . ":root {\n"
                . "    --background: #FAFAF8;\n"
                . "    --link-default: #2C5F94;\n"
                . "}\n",
            $css,
        );
    }

    public function testDeclarationsFollowTokenKeyOrderRatherThanInsertionOrder(): void
    {
        $reversed = new TokenSet(
            ThemeVariant::Light,
            new DesignToken(TokenKey::LinkDefault, new ColorValue('#2C5F94')),
            new DesignToken(TokenKey::Background, new ColorValue('#FAFAF8')),
        );
        $forwards = new TokenSet(
            ThemeVariant::Light,
            new DesignToken(TokenKey::Background, new ColorValue('#FAFAF8')),
            new DesignToken(TokenKey::LinkDefault, new ColorValue('#2C5F94')),
        );

        self::assertSame($this->writer->render($forwards), $this->writer->render($reversed));
    }

    public function testTheOutputIsByteIdenticalAcrossRuns(): void
    {
        self::assertSame($this->writer->render($this->tokens()), $this->writer->render($this->tokens()));
    }

    public function testEachVariantWritesItsOwnFileForTheSameTenant(): void
    {
        self::assertNotSame(
            $this->writer->targetPath($this->site, ThemeVariant::Light),
            $this->writer->targetPath($this->site, ThemeVariant::Dark),
        );
    }

    public function testStagingDoesNotPublishAndCommitDoes(): void
    {
        $target = $this->writer->targetPath($this->site, ThemeVariant::Light);

        $staged = $this->writer->stage($this->site, ThemeVariant::Light, $this->tokens());
        self::assertFileDoesNotExist($target);

        $this->files->commit($staged);
        self::assertSame($this->writer->render($this->tokens()), (string) file_get_contents($target));
    }

    public function testIsCurrentIsFalseBeforeAnythingIsWrittenAndTrueAfter(): void
    {
        self::assertNull($this->writer->currentContents($this->site, ThemeVariant::Light));
        self::assertFalse($this->writer->isCurrent($this->site, ThemeVariant::Light, $this->tokens()));

        $this->files->commit($this->writer->stage($this->site, ThemeVariant::Light, $this->tokens()));

        self::assertTrue($this->writer->isCurrent($this->site, ThemeVariant::Light, $this->tokens()));
    }

    public function testAPartialFileIsNeverObservableAtTheTargetPath(): void
    {
        $target = $this->writer->targetPath($this->site, ThemeVariant::Light);
        $this->files->commit($this->writer->stage($this->site, ThemeVariant::Light, $this->tokens()));
        $revisionOne = (string) file_get_contents($target);

        $next = new TokenSet(
            ThemeVariant::Light,
            new DesignToken(TokenKey::LinkDefault, new ColorValue('#1E4574')),
            new DesignToken(TokenKey::Background, new ColorValue('#FAFAF8')),
        );

        // Stage the replacement but abandon it, as a failed run would.
        $staged = $this->writer->stage($this->site, ThemeVariant::Light, $next);
        $this->writer->render($next);
        $this->files->discard($staged);

        self::assertSame($revisionOne, (string) file_get_contents($target));
        self::assertSame(['branding/alpha/tokens-light.css'], $this->filesUnder($this->tree));
    }
}
